sudo: false
os: linux
language: python

git:
  depth: 3
  submodules: false

branches:
  only: master

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install: pip install tox

script: tox
