sudo: false
os: linux
language: python

git:
  depth: 3
  submodules: false

branches:
  only: master

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r dev-requirements.txt --upgrade

build:
  - python3 setup.py sdist bdist_wheel

script:
  - check-manifest
  - python3 setup.py check -m -s
  - pytest
