sudo: false
language: python

os: linux
dist: xenial

git:
  depth: 3
  submodules: false

branches:
  only: master

matrix:
  fast_finish: true

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install -r dev-requirements.txt --upgrade

install:
  - python3 setup.py sdist bdist_wheel
  - pip install -e .

before_script:
  - check-manifest
  - python3 setup.py check -m -s

script: pytest
