sudo: false
language: python

os: linux
dist: xenial

git:
  depth: 3
  submodules: false

branches:
  only: master

matrix:
  fast_finish: true

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r dev-requirements.txt --upgrade

build:
  - python3 setup.py sdist bdist_wheel

script:
  - check-manifest
  - python3 setup.py check -m -s
  - pip install -e .
  - pytest
