FROM sadm

LABEL maintainer="Jeremías Casteglione <jrmsdev@gmail.com>"
LABEL version="0.1"

USER root:root

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get clean
RUN apt-get update

RUN apt-get dist-upgrade -y --purge
RUN apt-get install -y --no-install-recommends python3-pip

COPY venv/requirements-test.txt /tmp
COPY venv/requirements.txt /tmp

RUN pip3 install -r /tmp/requirements-test.txt
RUN pip3 install -r /tmp/requirements.txt

RUN apt-get clean
RUN apt-get autoremove -y --purge

RUN rm -rf /var/lib/apt/lists/*
RUN rm -f /var/cache/apt/archives/*.deb
RUN rm -f /var/cache/apt/*cache.bin

###RUN echo '/opt/src/sadm' >/usr/local/lib/python3.5/dist-packages/sadm.egg-link
###RUN echo 'export PYTHONPATH=/opt/src/sadm' >>/home/sadm/.bashrc

USER sadm:sadm
WORKDIR /opt/src/sadm

CMD /bin/bash
