FROM jrmsdev/sadm:test

LABEL maintainer="Jeremías Casteglione <jrmsdev@gmail.com>"
LABEL version="19.7.26"

USER root:root

COPY venv/requirements-dev.txt /tmp
RUN pip3 install -r /tmp/requirements-dev.txt

RUN rm -rf /root/.cache
RUN rm -f /tmp/requirements-dev.txt

USER sadm:sadm
WORKDIR /opt/src/sadm

CMD /bin/bash -i -l
